package com.mohamedtaha.imagine.ui.home.viewModel

import android.content.Context
import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.ViewModel
import com.mohamedtaha.imagine.R
import com.mohamedtaha.imagine.mvp.model.ImageModel
import dagger.hilt.android.lifecycle.HiltViewModel
import javax.inject.Inject

@HiltViewModel
class ReaderViewModel @Inject constructor(): ViewModel(){
    private val _sound = MutableLiveData<List<ImageModel>>()
    val sound get() = _sound
    fun getData(context: Context) {
        val images = ArrayList<ImageModel>()
        images.add(
            ImageModel(
                context.getString(R.string.dokaly_mohamed),
                R.drawable.aldokaly_mohamed,
                context.getString(R.string.qalon_an_nafea),
                0
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.elzen_mohamed),
                R.drawable.elzen_mohamed,
                context.getString(R.string.hafs_an_asem),
                1
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.al_ouoon_alkushi),
                R.drawable.al_ouoon_alkushi,
                context.getString(R.string.warsh_an_nafea),
                2
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.alfateh_mohamed),
                R.drawable.alfateh_mohamed,
                context.getString(R.string.aldawry_ebn_omar),
                3
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.shatri),
                R.drawable.shatri,
                context.getString(R.string.hafs_an_asem),
                4
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.ahmed_elagamy),
                R.drawable.elagamy,
                context.getString(R.string.hafs_an_asem),
                5
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.ahmed_eltrabolsy),
                R.drawable.ahmed_khdr_eltrabolsy,
                context.getString(R.string.qalon_an_nafea),
                6
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.ahmed_eltrabolsy),
                R.drawable.ahmed_khdr_eltrabolsy,
                context.getString(R.string.hafs_an_asem),
                7
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.ahmed_elhawashy),
                R.drawable.ahmed_elhawashy,
                context.getString(R.string.hafs_an_asem),
                8
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.ahmed_saber),
                R.mipmap.logo,
                context.getString(R.string.hafs_an_asem),
                9
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.ahmed_amer),
                R.drawable.ahmed_amer,
                context.getString(R.string.hafs_an_asem),
                10
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.ahmed_naeane),
                R.drawable.ahmed_neanea,
                context.getString(R.string.hafs_an_asem),
                11
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.akram_al_aalakmi),
                R.drawable.akram_al_aalakmi,
                context.getString(R.string.hafs_an_asem),
                12
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.ibrahim_al_akhdar),
                R.drawable.ebrahem_khoder,
                context.getString(R.string.hafs_an_asem),
                13
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.ibrahim_al_dosary),
                R.drawable.ebrahem_eldosary,
                context.getString(R.string.hafs_an_asem),
                14
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.ibrahim_al_dosary),
                R.drawable.ebrahem_eldosary,
                context.getString(R.string.warsh_an_nafea),
                15
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.bnder_belela),
                R.drawable.belela,
                context.getString(R.string.hafs_an_asem),
                16
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.tawfik_sayegh),
                R.drawable.tawfik_sayegh,
                context.getString(R.string.hafs_an_asem),
                17
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.jamal_shaker),
                R.drawable.jamal_shaker,
                context.getString(R.string.hafs_an_asem),
                18
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.jaman_elesemy),
                R.drawable.jaman_elesemy,
                context.getString(R.string.hafs_an_asem),
                19
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.hatem_fared),
                R.drawable.hatem_fared,
                context.getString(R.string.hafs_an_asem),
                20
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.khaled_elmehana),
                R.drawable.khaled_elmehana,
                context.getString(R.string.hafs_an_asem),
                21
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.khaled_abdelkafy),
                R.drawable.khaled_abdelkafy,
                context.getString(R.string.hafs_an_asem),
                22
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.jleel),
                R.drawable.jleel,
                context.getString(R.string.hafs_an_asem),
                23
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.qht),
                R.drawable.qht,
                context.getString(R.string.hafs_an_asem),
                24
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.tnjy),
                R.drawable.tnjy,
                context.getString(R.string.hafs_an_asem),
                25
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.ramy_eldabs),
                R.mipmap.logo,
                context.getString(R.string.hafs_an_asem),
                26
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.zaki_daghistani),
                R.drawable.zaki_daghistani,
                context.getString(R.string.hafs_an_asem),
                27
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.sahl_yassen),
                R.drawable.sahl_yassen,
                context.getString(R.string.hafs_an_asem),
                28
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.s_gmd),
                R.drawable.s_gmd,
                context.getString(R.string.hafs_an_asem),
                29
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.saad),
                R.mipmap.logo,
                context.getString(R.string.hafs_an_asem),
                30
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.soud_elsherem),
                R.drawable.sherem,
                context.getString(R.string.hafs_an_asem),
                31
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.sayed),
                R.drawable.syed_rmdan,
                context.getString(R.string.hafs_an_asem),
                32
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.taher),
                R.drawable.taher,
                context.getString(R.string.hafs_an_asem),
                33
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.hkm),
                R.drawable.hkm,
                context.getString(R.string.hafs_an_asem),
                34
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.salah_hashim_m),
                R.drawable.salah_hashim_m,
                context.getString(R.string.hafs_an_asem),
                35
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.slah_elbadry),
                R.drawable.bder,
                context.getString(R.string.hafs_an_asem),
                36
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.bu_khtr),
                R.drawable.bu_khtr,
                context.getString(R.string.hafs_an_asem),
                37
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.tareq),
                R.drawable.tarek_abdelany,
                context.getString(R.string.qalon_an_nafea),
                38
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.ryan),
                R.drawable.ryan,
                context.getString(R.string.hafs_an_asem),
                39
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.adel_elkalbany),
                R.drawable.elklbany,
                context.getString(R.string.hafs_an_asem),
                40
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.abdelbaset),
                R.drawable.abdeelbaset,
                context.getString(R.string.hafs_an_asem),
                41
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.abdelbaset),
                R.drawable.abdeelbaset,
                context.getString(R.string.warsh_an_nafea),
                42
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.abdelbaset),
                R.drawable.abdeelbaset,
                context.getString(R.string.ekmoshaf_elmogawad),
                43
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.abdellah_elgeheny),
                R.drawable.elgeheny,
                context.getString(R.string.hafs_an_asem),
                44
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.abdelrhman_elqasem),
                R.drawable.elqasem,
                context.getString(R.string.hafs_an_asem),
                45
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.abdelrshed_sofy),
                R.drawable.soufi_hfs,
                context.getString(R.string.alsosy_ebn_omar),
                46
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.abdelrshed_sofy),
                R.drawable.soufi_hfs,
                context.getString(R.string.khalaf_ben_hamza),
                47
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.abdelazez_elzahrany),
                R.drawable.abdelazez_elzahrany,
                context.getString(R.string.hafs_an_asem),
                48
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.abdelbara_elthebety),
                R.drawable.abdelbara_elthebety,
                context.getString(R.string.hafs_an_asem),
                49
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.abdelrhman_elosa),
                R.drawable.abdelrhman_elosa,
                context.getString(R.string.hafs_an_asem),
                50
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.bari),
                R.drawable.abdelbary,
                context.getString(R.string.hafs_an_asem),
                51
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.abdelrhman_elsodes),
                R.drawable.elsodes,
                context.getString(R.string.hafs_an_asem),
                52
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.a_majed),
                R.drawable.a_majed,
                context.getString(R.string.hafs_an_asem),
                53
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.soufi_hfs),
                R.drawable.soufi_hfs,
                context.getString(R.string.hafs_an_asem),
                54
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.a_ahmed),
                R.drawable.a_ahmed,
                context.getString(R.string.hafs_an_asem),
                55
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.khalf),
                R.drawable.khalf,
                context.getString(R.string.hafs_an_asem),
                56
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.abdullahk),
                R.drawable.abdullahk,
                context.getString(R.string.hafs_an_asem),
                57
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.bsfr),
                R.drawable.bsfr,
                context.getString(R.string.hafs_an_asem),
                58
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.kyat),
                R.drawable.kyat,
                context.getString(R.string.hafs_an_asem),
                59
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.gulan),
                R.drawable.gulan,
                context.getString(R.string.hafs_an_asem),
                60
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.mohsin_harthi),
                R.drawable.mohsin_harthi,
                context.getString(R.string.hafs_an_asem),
                61
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.obk),
                R.drawable.obk,
                context.getString(R.string.hafs_an_asem),
                62
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.kanakeri),
                R.drawable.kanakeri,
                context.getString(R.string.hafs_an_asem),
                63
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.wdod),
                R.drawable.wdod,
                context.getString(R.string.hafs_an_asem),
                64
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.a_jbr),
                R.drawable.a_jbr,
                context.getString(R.string.hafs_an_asem),
                65
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.ali_elhozefy),
                R.drawable.ali_elhozefy,
                context.getString(R.string.qalon_an_nafea),
                66
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.ali_elhozefy),
                R.drawable.ali_elhozefy,
                context.getString(R.string.hafs_an_asem),
                67
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.ali_swiesy),
                R.drawable.ali_swiesy,
                context.getString(R.string.hafs_an_asem),
                68
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.hafz),
                R.drawable.hafz,
                context.getString(R.string.hafs_an_asem),
                69
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.omar_kzabri),
                R.drawable.omar_kzabri,
                context.getString(R.string.warsh_an_nafea),
                70
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.frs_a),
                R.drawable.frs_a,
                context.getString(R.string.hafs_an_asem),
                71
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.maher_elmeaqly),
                R.drawable.almaqely,
                context.getString(R.string.hafs_an_asem),
                72
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.shaksh),
                R.drawable.shaksh,
                context.getString(R.string.hafs_an_asem),
                73
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.ayyub),
                R.drawable.ayyub,
                context.getString(R.string.hafs_an_asem),
                74
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.m_krm),
                R.drawable.m_krm,
                context.getString(R.string.hafs_an_asem),
                75
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.m_krm),
                R.drawable.m_krm,
                context.getString(R.string.warsh_an_nafea_by_abe_bakr),
                76
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.earawi),
                R.drawable.earawi,
                context.getString(R.string.warsh_an_nafea_by_abe_bakr),
                77
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.shah),
                R.drawable.shah,
                context.getString(R.string.hafs_an_asem),
                78
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.rashad),
                R.drawable.rashad,
                context.getString(R.string.hafs_an_asem),
                79
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.lhdan),
                R.drawable.lhdan,
                context.getString(R.string.hafs_an_asem),
                80
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.khan),
                R.mipmap.logo,
                context.getString(R.string.hafs_an_asem),
                81
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.mohamed_elmenshawyM),
                R.drawable.elmenshawy,
                context.getString(R.string.ekmoshaf_elmogawad),
                82
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.mohamed_elmenshawyH),
                R.drawable.elmenshawy,
                context.getString(R.string.hafs_an_asem),
                83
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.mohamed_eltblawy),
                R.drawable.eltblawy,
                context.getString(R.string.hafs_an_asem),
                84
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.mohamed_abd_elhakem),
                R.drawable.mohamed_abd_elhakem,
                context.getString(R.string.elbezy_an_ebnkaser),
                85
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.mohamed_abd_elhakem),
                R.drawable.mohamed_abd_elhakem,
                context.getString(R.string.aldawry_an_elkasai),
                86
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.mohamed_gebrer),
                R.drawable.mohamedgbrer,
                context.getString(R.string.hafs_an_asem),
                87
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.mshary_elafasy),
                R.drawable.msharyelafasy,
                context.getString(R.string.hafs_an_asem),
                88
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.mrifai),
                R.drawable.mrifai,
                context.getString(R.string.hafs_an_asem),
                89
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.sheimy),
                R.drawable.sheimy,
                context.getString(R.string.aldawry_an_elkasai),
                90
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.mahmoud_elhosaryM),
                R.drawable.elhosary,
                context.getString(R.string.ekmoshaf_elmogawad),
                91
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.mahmoud_elhosaryM),
                R.drawable.elhosary,
                context.getString(R.string.warsh_an_nafea),
                92
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.mahmoud_elhosaryH),
                R.drawable.elhosary,
                context.getString(R.string.hafs_an_asem),
                93
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.mahmoud_elbana),
                R.drawable.elbana,
                context.getString(R.string.hafs_an_asem),
                94
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.mahmoud_elbana),
                R.drawable.elbana,
                context.getString(R.string.ekmoshaf_elmogawad),
                95
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.mustafa),
                R.drawable.mustafa,
                context.getString(R.string.hafs_an_asem),
                96
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.lahoni),
                R.drawable.lahoni,
                context.getString(R.string.hafs_an_asem),
                97
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.ra3ad),
                R.drawable.ra3ad,
                context.getString(R.string.hafs_an_asem),
                98
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.harthi),
                R.mipmap.logo,
                context.getString(R.string.hafs_an_asem),
                99
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.moftah_elslty),
                R.drawable.moftah_elslty,
                context.getString(R.string.aldawry_an_elkasai),
                100
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.moftah_elslty),
                R.drawable.moftah_elslty,
                context.getString(R.string.abnzakor),
                101
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.moftah_elslty),
                R.drawable.moftah_elslty,
                context.getString(R.string.hafs_an_asem),
                102
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.moftah_elslty),
                R.drawable.moftah_elslty,
                context.getString(R.string.aldawry_ebn_omar),
                103
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.bilal),
                R.drawable.bilal,
                context.getString(R.string.hafs_an_asem),
                104
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.naser_elqatamy),
                R.drawable.naserelqatamy,
                context.getString(R.string.hafs_an_asem),
                105
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.nasser_almajed),
                R.drawable.nasser_almajed,
                context.getString(R.string.hafs_an_asem),
                106
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.nabel_elrefaay),
                R.drawable.nabel_elrefaay,
                context.getString(R.string.hafs_an_asem),
                107
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.namh),
                R.drawable.namh,
                context.getString(R.string.hafs_an_asem),
                108
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.wadea_elyamany),
                R.drawable.wadea_elyamany,
                context.getString(R.string.hafs_an_asem),
                109
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.yaser_eldosary),
                R.drawable.eldosary,
                context.getString(R.string.hafs_an_asem),
                110
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.hani),
                R.drawable.hani,
                context.getString(R.string.hafs_an_asem),
                111
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.waled_elnaehy),
                R.mipmap.logo,
                context.getString(R.string.alon_ben_nafea),
                112
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.yaser_elmazroay),
                R.drawable.yaser_elmazroay,
                context.getString(R.string.yaqob_elhadrmy),
                113
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.yaser_elqarashy),
                R.drawable.elqarashy,
                context.getString(R.string.hafs_an_asem),
                114
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.salamah),
                R.drawable.salamah,
                context.getString(R.string.hafs_an_asem),
                115
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.yasen_elgazaery),
                R.drawable.yasen_elgazaery,
                context.getString(R.string.warsh_an_nafea),
                116
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.yahya),
                R.drawable.yahya,
                context.getString(R.string.hafs_an_asem),
                117
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.noah),
                R.drawable.noah,
                context.getString(R.string.hafs_an_asem),
                118
            )
        )
        images.add(
            ImageModel(
                context.getString(R.string.yosem_elshereay),
                R.drawable.yosem_elshereay,
                context.getString(R.string.hafs_an_asem),
                119
            )
        )
        _sound.value = images
    }

}